### ISSUE TITLE
First message sent in a while must be sent twice

### ISSUE THREAD

**Issue by spwhitton** [jgeboski/bitlbee-facebook#53] opened 2015-11-27 16:05 UTC
I recently upgraded to Debian package version `20151113~f2ca48a~16` from Arch package version `r54.094a11b-1`, so I think this means an upgrade from the git master branch of 2015-08-28 to the git master branch of 2015-11-13.  I'm running the new version on Debian Jessie 32-bit.

Sometimes when I haven't sent a message to someone in a while, I have to send the message twice in my IRC client or it won't reach them.  Then for a few minutes I can send messages once.  There's no disconnections given in the status window during this period.  How can I help you debug this?

Thanks, jgeboski, for a great Bitlbee plugin.

**Comment by dequis** [comment] 2015-11-27 18:38
Stop the bitlbee daemon (either correctly or `killall bitlbee`), and run the following as the correct user (probably a matter of adding `sudo -u bitlbee` after `BITLBEE_DEBUG=1`)

```
$ BITLBEE_DEBUG=1 bitlbee -Dnv 2>&1 > bitlbee.log
```

Connect with your irc client, wait a minute to ensure there's some space between login and the messages, and try to reproduce the issue (ideally sending one message that gets lost, one message that is received, and nothing else, but some other noise is), and ctrl-c bitlbee.

Then either try to cut the last part to only have the messages and maybe a few presences, or just email the whole thing to jgeboski@gmail.com (and I wouldn't mind a CC to dx@dxzone.com.ar if it's only the last part).

Note that if you do decide to email the whole thing, it will probably have your password, and whatever you do it will have user IDs all over the place. Cleaning these logs is hard. Just don't post it publicly.

**Comment by spwhitton** [comment] 2015-11-28 21:09
Thanks for the feedback.  Today I'm not getting the issue.  I'll keep an
eye out and submit those logs if I observe it happening again.

**Comment by spwhitton** [comment] 2015-11-29 23:40
You got mail.

**Comment by dequis** [comment] 2015-11-29 23:52
Any messages in &bitlbee while this happened?

**Comment by dequis** [comment] 2015-11-30 00:04
Nevermind, I think i know what happened. Potential workaround: `account facebook set away yes`. Will make you appear invisible all the time but probably avoids this problem.

**Comment by jgeboski** [comment] 2015-11-30 00:25
As discovered by @dequis, this is due to the silent reconnection which takes place when toggling the invisibility state (there is no way around the reconnection). Resolving this issue will require the messages to be queued when reconnecting. That said, the messages also need to be queued for silent reconnections upon an error (#28). I would like there to be single message queue, which waits for an acknowledgement of a successful send for both forms of reconnecting.

This should not take terribly long, but right now I am kind of swamped. Hopefully in around three weeks, I will have time to start cranking out patches.

**Comment by spwhitton** [comment] 2015-11-30 02:33
Workaround seems good.  Thanks again for your efforts on bitlbee-facebook.

**Comment by jgeboski** [comment] 2016-01-07 19:20
This has been resolved as of 074cfd5.

**Closed by jgeboski** 2016-01-07 19:20 UTC
Labels: bug

**Comment by spwhitton** [comment] 2016-01-07 19:39
Thank you very much for your work on this fine piece of software.
