### ISSUE TITLE
Disconnecting with error: Short read

### ISSUE THREAD

**Issue by toogy** [jgeboski/bitlbee-facebook#28] opened 2015-05-19 12:40 UTC
Hey. I'm back with a new bug!
```
14:38 <@root> facebook - Error: Short read
14:38 <@root> facebook - Signing off..
14:38 <@root> facebook - Reconnecting in 5 seconds..
14:38 <@root> facebook - Logging in: Connecting
14:38 <@root> facebook - Logging in: Fetching contacts
14:38 <@root> facebook - Logging in: Establishing connection
14:38 <@root> facebook - Logging in: Logged in
```

I'm constantly getting disconnected with this error.
I'm using the last version from master (also tried development branch).
I tried:

+ rebuilding
+ removing the account...
+ restarting bitlbee
+ logging off and back in...

**Comment by toogy** [comment] 2015-05-19 12:44
Probably related to #10 which was supposed to be resolved.

**Comment by jgeboski** [comment] 2015-05-19 18:05
Is your network connection dying?

**Comment by dequis** [comment] 2015-05-19 23:01
How often is "constantly", precisely?

**Comment by toogy** [comment] 2015-05-20 12:06
My network connection is not dying. bitlbee and my irc client are running in a tmux session in a datacenter.

Constantly means every 10 minutes.

**Comment by toogy** [comment] 2015-05-21 12:43
```log
[bitlbee-facebook] Reading message (topic: /inbox):
[bitlbee-facebook]   00000000  7b 22 75 6e 72 65 61 64  22 3a 35 2c 22 75 6e 73  |{"unread":5,"uns|
[bitlbee-facebook]   00000010  65 65 6e 22 3a 31 2c 22  6f 74 68 65 72 5f 75 6e  |een":1,"other_un|
[bitlbee-facebook]   00000020  73 65 65 6e 22 3a 30 2c  22 6f 74 68 65 72 5f 75  |seen":0,"other_u|
[bitlbee-facebook]   00000030  6e 72 65 61 64 22 3a 30  2c 22 73 65 65 6e 5f 74  |nread":0,"seen_t|
[bitlbee-facebook]   00000040  69 6d 65 73 74 61 6d 70  22 3a 30 2c 22 72 65 61  |imestamp":0,"rea|
[bitlbee-facebook]   00000050  6c 74 69 6d 65 5f 76 69  65 77 65 72 5f 66 62 69  |ltime_viewer_fbi|
[bitlbee-facebook]   00000060  64 22 3a 31 30 30 30 30  37 30 32 30 31 38 31 38  |d":XXXXXXXXXXXXX|
[bitlbee-facebook]   00000070  33 32 2c 22 74 79 70 65  22 3a 22 69 6e 62 6f 78  |32,"type":"inbox|
[bitlbee-facebook]   00000080  22 7d                                             |"}|
[bitlbee-facebook]   00000090
[bitlbee-facebook] Error: Short read
[bitlbee-facebook] Writing 14 (flags: 0x0)
[bitlbee-facebook]   00000000  e0 00                                             |..|
[bitlbee-facebook]   00000010
[bitlbee-facebook] Closing with unwritten data
[bitlbee-facebook] POST Request (0x7f82cb9cbf00): https://graph.facebook.com:443/graphql
[bitlbee-facebook]   User-Agent: Facebook App / BitlBee / 0.1.0
[bitlbee-facebook]   Content-Length: 266
[bitlbee-facebook]   Connection: Close
[bitlbee-facebook]   Accept: */*
[bitlbee-facebook]   Content-Type: application/x-www-form-urlencoded
[bitlbee-facebook]   Host: graph.facebook.com
[bitlbee-facebook]   Authorization: OAuth XXX
[bitlbee-facebook]
[bitlbee-facebook]   fb_api_req_friendly_name=FetchContactsFullQuery&[BLABLABLA]
[bitlbee-facebook] POST Response (0x7f82cb9cbf00): https://graph.facebook.com:443/graphql (Error while writing HTTP request)
[bitlbee-facebook]   ** No header data **
[bitlbee-facebook]
[bitlbee-facebook]   ** No body data **
[bitlbee-facebook] POST Request (0x7f82cb9cbf00): https://graph.facebook.com:443/graphql
```

**Comment by toogy** [comment] 2015-05-22 22:37
So, it was happening constantly at the time of the report but now it's far more infrequent.
Everyone seems to get short reads from time to time.
Looks like it is Facebook servers' fault.
Is there a way for bitlbee-facebook to handle these disconnections transparently and act as if nothing happened?

**Comment by jgeboski** [comment] 2015-07-02 18:53
Does this still happen?

**Comment by blaskovic** [comment] 2015-07-13 21:51
Same problem on CentOS7 with bitlbee-3.2.2-3.el7.x86_64 and current master of this repo.

**Comment by dequis** [comment] 2015-07-13 21:56
Note that getting disconnected with "short read" usually just means getting disconnected normally. If it happens once every few hours it's not a bug.

**Comment by blaskovic** [comment] 2015-07-13 22:05
Well ok. But everytime all my group fb chats are like this:

    23:43:02 -!- Netsplit localhost.localdomain <-> chat.facebook.com quits: UserFromChat
    23:43:02 <@root> Cleaning up channel, bye!
    23:43:02 -!- MyNick was kicked from #channel by root [Chatroom closed by server]

And I have to /join #channel back manually. Which is really annoying.

**Comment by dequis** [comment] 2015-07-13 22:08
How about `channel #channel set auto_join true`

**Comment by blaskovic** [comment] 2015-07-13 22:15
I will give it a try and provide report after few hours.

**Comment by blaskovic** [comment] 2015-07-14 07:19
Ok, auto rejoin works but now I just see nothing else than rejoins every few minutes/hours. This is not a solution.

**Comment by dequis** [comment] 2015-07-14 22:42
>I just see nothing else than rejoins every few minutes/hours

What do you mean? You stop receiving chat messages from the auto-rejoined channel?

**Comment by blaskovic** [comment] 2015-07-15 12:31
I am receiving them but for example after night when nobody is writing, my backlog is full of rejoins. And maybe somewhere between them are some messages which I can overlook.

**Comment by jgeboski** [comment] 2016-01-07 19:22
We really have no control over this happening, but as of ef58beb, the plugin will attempt to silently reconnect. This should alleviate this issue for the most part.

**Closed by jgeboski** 2016-01-07 19:22 UTC
