### ISSUE TITLE
New friends not recognised

### ISSUE THREAD

**Issue by zippynk** [jgeboski/bitlbee-facebook#52] opened 2015-11-10 18:26 UTC
When a new friend is added via another interface (e.g the Facebook website), Bitlbee doesn't recognise them and marks their online/offline status changes with messages from root instead of adding them to the buddy list. Disabling and re-enabling the account fixes this.

Example:

`2015-10-30 00:00:22	@root	facebook - imcb_buddy_status() for unknown handle [facebook user id redacted]:`

**Comment by dequis** [comment] 2015-11-10 18:32
#22 was the same thing as this, but it got closed as a dupe of the TODO ticket, and now the TODO ticket is closed.

**Comment by jgeboski** [comment] 2015-11-10 18:48
When a user is friended or defriended, no events are sent over the MQTT stream. This is because the Messenger protocol is simply thread based, rather than friend based. As a result, we have to refetch the friend list every so often, which is done every 30 minutes. This can be set as low as five minutes with `account facebook set sync_interval 5`.

To resolve this issue, it is probably best we also refetch on an unknown handle as well.

**Comment by jgeboski** [comment] 2016-01-03 21:24
@zippynk what version of the plugin are you running?

**Comment by jgeboski** [comment] 2016-01-16 14:40
Closing due to lack of reply. I have also tested this, and it appears to work fine for me, even with a `sync_interval` of `30`.

**Closed by jgeboski** 2016-01-16 14:40 UTC

**Comment by zippynk** [comment] 2016-01-18 03:13
Sorry, looks like I overlooked your last 2 posts. The issue seems to have gone away now as far as I can tell.



For record purposes:

The server I was using at the time I submitted this is im.codemonkey.be; I can't figure out what version it runs now or the version it did then.
The server I'm using now (self-hosted) is running plugin version 20151223~3e09957~172.
